export const timeline_data = [
    {
        id: "1",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View ",
        date : "August 2016 - present",
        icon : "work",
      },
      {
        id: "2",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View ",
        date : "August 2016 - present",
        icon : "school",
      },
      {
        id: "3",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View ",
        date : "August 2016 - present",
        icon : "work",
      },
      {
        id: "4",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View ",
        date : "August 2016 - present",
        icon : "school",
      },
      {
        id: "5",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View",
        date : "August 2016 - present",
        icon : "work",
      },
      {
        id: "6",
        title : "Frontend Developer",
        location : "Surat",
        description : "Adipisicing repellat eius distinctio amet consequuntur incididunt gravida ipsam tincidunt anim mauris, praesentium occaecati!",
        buttonText : "View",
        date : "August 2016 - present",
        icon : "school",
      },
]